### ISSUE TITLE
Rendering over tooltips

### ISSUE THREAD

**Issue by Darkere** [ShayBox/Durability101#3]
The durability numbers render over tooltips making them look weird. 

![image](https://user-images.githubusercontent.com/4283717/75792258-fadfa280-5d6d-11ea-8638-9b48c3681734.png)

Forge: 31.1.18
Durability101-1.15-0.0.3

**Comment by ShayBox** [comment]
I just saw this bug on a youtube video, seems it might be a vanilla issue, but I haven't been able to recreate it
![image](https://user-images.githubusercontent.com/9505196/83132368-4e346900-a0af-11ea-8677-12b4b640e590.png)

**Comment by Trnrr** [comment]
Hello I just wanted to say I also get this issue on forge 1.16 32.0.75 & durability101-1.16-0.0.3. 
![image](https://user-images.githubusercontent.com/20446954/88463739-a05cf500-ce7a-11ea-97ca-8facfe2ae548.png)

**Comment by pajicadvance** [comment]
Happens on Fabric as well. durability101-1.16-0.0.3, fabric loader 0.9.0 build 204
![2020-08-09_00-47](https://user-images.githubusercontent.com/32738446/89721124-1a908c00-d9da-11ea-903d-befbc826d528.png)

**Comment by ZephaniahNoah** [comment]
It looks like you are doing your translate too high. `matrices.translate(0.0D, 0.0D, 500.0F);` am I wrong? 500 is really high.

**Comment by ZephaniahNoah** [comment]
I cloned the repo and tested some numbers in debug mode. It seems 258 is the perfect z level. It's high enough to not clip into blocks. It might clip into some models from other mods though. Tooltips are rendered at z level 400. So anything between these two numbers should be fine.

**Comment by ShayBox** [comment]
Earlier versions of Minecraft don't have z-translation problems, however around 1.13-1.15 they switched to a new rendering engine, however they dynamically add to a z-offset variable, which is hard to get access to, and with other mods and coremods messing with it, it can be hard to find a single good value, I just rebased all versions of my mod and tested every version, 750 works both in dev and a fresh install of every version, so if it's broken now it's because of another mod or older modloader version than latest, hopefully this fixes it for you.

**Comment by Laifsyn** [comment]
![image](https://github.com/ShayBox/Durability101/assets/99366187/778b0d66-1e6c-42af-8d38-cba00537f72a)
I have a funnier image example here.
I suggest as immediate solution a button to toggle its rendering
